apiVersion: v1
kind: Service
metadata:
  name: home
  labels:
    app: home
    service: home
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: home
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-v1
  labels:
    app: home
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
      version: v1
  template:
    metadata:
      labels:
        app: home
        version: v1
    spec:
      containers:
      - name: home:1
        image: 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        securityContext:
          runAsUser: 1000
---
##################################################################################################
# Ratings service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: board
  labels:
    app: board
    service: board
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: board
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-v1
  labels:
    app: board
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board
      version: v1
  template:
    metadata:
      labels:
        app: board
        version: v1
    spec:
      serviceAccountName: bookinfo-board
      containers:
      - name: board:1
        image: 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        securityContext:
          runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: grad-db
  labels:
    app: grad-db
    service: grad-db
spec:
  ports:
  - port: 3306
    name: tcp
  selector:
    app: grad-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grad-db-v1
  labels:
    app: grad-db
    version: mysql-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grad-db
      version: mysql-v1
  template:
    metadata:
      labels:
        app: grad-db
        version: mysql-v1
    spec:
      serviceAccountName: bookinfo-grad-db
      containers:
      - name: grad-db:1
        image: 
        imagePullPolicy: IfNotPresent
        env:
          # This assumes you registered your mysql vm as
          # istioctl register -n vm mysqldb 1.2.3.4 3306
          - name: DB_TYPE
            value: "mysql"
          - name: MYSQL_DB_HOST
            value: mysqldb.vm.svc.cluster.local
          - name: MYSQL_DB_PORT
            value: "3306"
          - name: MYSQL_DB_USER
            value: root
          - name: MYSQL_DB_PASSWORD
            value: password
        ports:
        - containerPort: 3306
        securityContext:
          runAsUser: 1000
---
